In [1]:
%pip install ucimlrepo

Requirement already satisfied: ucimlrepo in c:\Users\test\AppData\Local\Programs\Python\Python313\Lib\site-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in c:\Users\test\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ucimlrepo) (3.0.2)
Requirement already satisfied: certifi>=2020.12.5 in c:\Users\test\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ucimlrepo) (2026.1.4)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\test\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\test\AppData\Roaming\Python\Python313\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\test\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2026.1)
Requirement already satisfied: six>=1.5 in C:\Users\test\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
from ucimlrepo import fetch_ucirepo 
import pandas as pd

In [18]:
# fetch dataset 
diabetes_130_us_hospitals_for_years_1999_2008 = fetch_ucirepo(id=296) 
  
# data (as pandas dataframes) 
X = diabetes_130_us_hospitals_for_years_1999_2008.data.features 
y = diabetes_130_us_hospitals_for_years_1999_2008.data.targets 
  
# metadata 
print(diabetes_130_us_hospitals_for_years_1999_2008.metadata) 
  
# variable information 
print(diabetes_130_us_hospitals_for_years_1999_2008.variables)

{'uci_id': 296, 'name': 'Diabetes 130-US Hospitals for Years 1999-2008', 'repository_url': 'https://archive.ics.uci.edu/dataset/296/diabetes+130-us+hospitals+for+years+1999-2008', 'data_url': 'https://archive.ics.uci.edu/static/public/296/data.csv', 'abstract': 'The dataset represents ten years (1999-2008) of clinical care at 130 US hospitals and integrated delivery networks. Each row concerns hospital records of patients diagnosed with diabetes, who underwent laboratory, medications, and stayed up to 14 days. The goal is to determine the early readmission of the patient within 30 days of discharge.\nThe problem is important for the following reasons. Despite high-quality evidence showing improved clinical outcomes for diabetic patients who receive various preventive and therapeutic interventions, many patients do not receive them. This can be partially attributed to arbitrary diabetes management in hospital environments, which fail to attend to glycemic control. Failure to provide proper diabetes care not only increases the managing costs for the hospitals (as the patients are readmitted) but also impacts the morbidity and mortality of the patients, who may face complications associated with diabetes.\n', 'area': 'Health and Medicine', 'tasks': ['Classification', 'Clustering'], 'characteristics': ['Multivariate'], 'num_instances': 101766, 'num_features': 47, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Race', 'Gender', 'Age'], 'target_col': ['readmitted'], 'index_col': ['encounter_id', 'patient_nbr'], 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 2014, 'last_updated': 'Tue Sep 24 2024', 'dataset_doi': '10.24432/C5230J', 'creators': ['John Clore', 'Krzysztof Cios', 'Jon DeShazo', 'Beata Strack'], 'intro_paper': {'ID': 225, 'type': 'NATIVE', 'title': 'Impact of HbA1c Measurement on Hospital Readmission Rates: Analysis of 70,000 Clinical Database Patient Record', 'authors': 'Beata Strack, Jonathan DeShazo, Chris Gennings, Juan Olmo, Sebastian Ventura, Krzysztof Cios, John Clore', 'venue': 'BioMed Research International, vol. 2014', 'year': 2014, 'journal': None, 'DOI': None, 'URL': 'https://www.hindawi.com/journals/bmri/2014/781670/', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'The dataset represents ten years (1999-2008) of clinical care at 130 US hospitals and integrated delivery networks. It includes over 50 features representing patient and hospital outcomes. Information was extracted from the database for encounters that satisfied the following criteria.\n(1)\tIt is an inpatient encounter (a hospital admission).\n(2)\tIt is a diabetic encounter, that is, one during which any kind of diabetes was entered into the system as a diagnosis.\n(3)\tThe length of stay was at least 1 day and at most 14 days.\n(4)\tLaboratory tests were performed during the encounter.\n(5)\tMedications were administered during the encounter.\n\nThe data contains such attributes as patient number, race, gender, age, admission type, time in hospital, medical specialty of admitting physician, number of lab tests performed, HbA1c test result, diagnosis, number of medications, diabetic medications, number of outpatient, inpatient, and emergency visits in the year before the hospitalization, etc.', 'purpose': None, 'funded_by': None, 'instances_represent': 'The instances represent hospitalized patient records diagnosed with diabetes.', 'recommended_data_splits': 'No recommendation. The standard train-test split could be used. Can use three-way holdout split (i.e., train-validation-test) when doing model selection.', 'sensitive_data': 'Yes. The dataset contains information about the age, gender, and race of the patients.', 'preprocessing_description': None, 'variable_info': 'Detailed description of all the atrributes is provided in Table 1 Beata Strack, Jonathan P. DeShazo, Chris Gennings,  Juan L. Olmo, Sebastian Ventura,  Krzysztof J. Cios, and John N. Clore, “Impact of HbA1c Measurement on Hospital Readmission Rates: Analysis of 70,000 Clinical Database Patient Records,” BioMed Research International, vol. 2014, Article ID 781670, 11 pages, 2014.\n\nhttp://www.hindawi.com/journals/bmri/2014/781670/', 'citation': 'Please cite:\nBeata Strack, Jonathan P. DeShazo, Chris Gennings, Juan L. Olmo, Sebastian Ventura, Krzysztof J. Cios, and John N. Clore, “Impact of HbA1c Measurement on Hospital Readmission Rates: Analysis of 70,000 Clinical Database Patient Records,” BioMed Research International, vol. 2014, Article ID 781670, 11 pages, 2014.'}}
                        name     role         type demographic  \
0               encounter_id       ID                      NaN
1                patient_nbr       ID                      NaN
2                       race  Feature  Categorical        Race
3                     gender  Feature  Categorical      Gender
4                        age  Feature  Categorical         Age
5                     weight  Feature  Categorical         NaN
6          admission_type_id  Feature  Categorical         NaN
7   discharge_disposition_id  Feature  Categorical         NaN
8        admission_source_id  Feature  Categorical         NaN
9           time_in_hospital  Feature      Integer         NaN
10                payer_code  Feature  Categorical         NaN
11         medical_specialty  Feature  Categorical         NaN
12        num_lab_procedures  Feature      Integer         NaN
13            num_procedures  Feature      Integer         NaN
14           num_medications  Feature      Integer         NaN
15         number_outpatient  Feature      Integer         NaN
16          number_emergency  Feature      Integer         NaN
17          number_inpatient  Feature      Integer         NaN
18                    diag_1  Feature  Categorical         NaN
19                    diag_2  Feature  Categorical         NaN
20                    diag_3  Feature  Categorical         NaN
21          number_diagnoses  Feature      Integer         NaN
22             max_glu_serum  Feature  Categorical         NaN
23                 A1Cresult  Feature  Categorical         NaN
24                 metformin  Feature  Categorical         NaN
25               repaglinide  Feature  Categorical         NaN
26               nateglinide  Feature  Categorical         NaN
27            chlorpropamide  Feature  Categorical         NaN
28               glimepiride  Feature  Categorical         NaN
29             acetohexamide  Feature  Categorical         NaN
30                 glipizide  Feature  Categorical         NaN
31                 glyburide  Feature  Categorical         NaN
32               tolbutamide  Feature  Categorical         NaN
33              pioglitazone  Feature  Categorical         NaN
34             rosiglitazone  Feature  Categorical         NaN
35                  acarbose  Feature  Categorical         NaN
36                  miglitol  Feature  Categorical         NaN
37              troglitazone  Feature  Categorical         NaN
38                tolazamide  Feature  Categorical         NaN
39                   examide  Feature  Categorical         NaN
40               citoglipton  Feature  Categorical         NaN
41                   insulin  Feature  Categorical         NaN
42       glyburide-metformin  Feature  Categorical         NaN
43       glipizide-metformin  Feature  Categorical         NaN
44  glimepiride-pioglitazone  Feature  Categorical         NaN
45   metformin-rosiglitazone  Feature  Categorical         NaN
46    metformin-pioglitazone  Feature  Categorical         NaN
47                    change  Feature  Categorical         NaN
48               diabetesMed  Feature  Categorical         NaN
49                readmitted   Target  Categorical         NaN

                                          description units missing_values
0                   Unique identifier of an encounter  None             no
1                      Unique identifier of a patient  None             no
2   Values: Caucasian, Asian, African American, Hi...  None            yes
3           Values: male, female, and unknown/invalid  None             no
4   Grouped in 10-year intervals: [0, 10), [10, 20...  None             no
5                                   Weight in pounds.  None            yes
6   Integer identifier corresponding to 9 distinct...  None             no
7   Integer identifier corresponding to 29 distinc...  None             no
8   Integer identifier corresponding to 21 distinc...  None             no
9   Integer number of days between admission and d...  None             no
10  Integer identifier corresponding to 23 distinc...  None            yes
11  Integer identifier of a specialty of the admit...  None            yes
12  Number of lab tests performed during the encou...  None             no
13  Number of procedures (other than lab tests) pe...  None             no
14  Number of distinct generic names administered ...  None             no
15  Number of outpatient visits of the patient in ...  None             no
16  Number of emergency visits of the patient in t...  None             no
17  Number of inpatient visits of the patient in t...  None             no
18  The primary diagnosis (coded as first three di...  None            yes
19  Secondary diagnosis (coded as first three digi...  None            yes
20  Additional secondary diagnosis (coded as first...  None            yes
21          Number of diagnoses entered to the system  None             no
22  Indicates the range of the result or if the te...  None             no
23  Indicates the range of the result or if the te...  None             no
24  The feature indicates whether the drug was pre...  None             no
25  The feature indicates whether the drug was pre...  None             no
26  The feature indicates whether the drug was pre...  None             no
27  The feature indicates whether the drug was pre...  None             no
28  The feature indicates whether the drug was pre...  None             no
29  The feature indicates whether the drug was pre...  None             no
30  The feature indicates whether the drug was pre...  None             no
31  The feature indicates whether the drug was pre...  None             no
32  The feature indicates whether the drug was pre...  None             no
33  The feature indicates whether the drug was pre...  None             no
34  The feature indicates whether the drug was pre...  None             no
35  The feature indicates whether the drug was pre...  None             no
36  The feature indicates whether the drug was pre...  None             no
37  The feature indicates whether the drug was pre...  None             no
38  The feature indicates whether the drug was pre...  None             no
39  The feature indicates whether the drug was pre...  None             no
40  The feature indicates whether the drug was pre...  None             no
41  The feature indicates whether the drug was pre...  None             no
42  The feature indicates whether the drug was pre...  None             no
43  The feature indicates whether the drug was pre...  None             no
44  The feature indicates whether the drug was pre...  None             no
45  The feature indicates whether the drug was pre...  None             no
46  The feature indicates whether the drug was pre...  None             no
47  Indicates if there was a change in diabetic me...  None             no
48  Indicates if there was any diabetic medication...  None             no
49  Days to inpatient readmission. Values: <30 if ...  None             no

c:\Users\test\AppData\Local\Programs\Python\Python313\Lib\site-packages\ucimlrepo\fetch.py:97: DtypeWarning: Columns (0: payer_code) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_url)

In [ ]:
ids = diabetes_130_us_hospitals_for_years_1999_2008.data.ids
temp = ids.join(X)
df = temp.join(y)

In [ ]:
# save dataframe with original data
df.to_csv('original_data.csv')

In [22]:
print(df.columns)

Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'payer_code', 'medical_specialty',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted'],
      dtype='str')

In [23]:
print(df.groupby('weight').size())

weight
>200            3
[0-25)         48
[100-125)     625
[125-150)     145
[150-175)      35
[175-200)      11
[25-50)        97
[50-75)       897
[75-100)     1336
dtype: int64

In [24]:
# most common admitting medical specialties
df['medical_specialty'].value_counts(dropna=False)

medical_specialty
NaN                       49949
InternalMedicine          14635
Emergency/Trauma           7565
Family/GeneralPractice     7440
Cardiology                 5352
                          ...
Dermatology                   1
SportsMedicine                1
Speech                        1
Perinatology                  1
Neurophysiology               1
Name: count, Length: 73, dtype: int64

In [21]:
# find number of missing values for each column with missing values + overall percentage missing

# number of rows
n_rows = df.shape[0]
# column names 
columns = df.columns
col_percent_missing = []

# calculate percentage of missing values for each column 
for col in columns:
    col_na = df[col].isna().sum()
    col_percent = (col_na/n_rows)*100
    col_percent_missing.append((col, col_percent))

col_to_drop = []

# print columns with missing values
for col in col_percent_missing:
    if (col[1] > 0):
        print(f'{col[0]}: {col[1]:.2f}% missing')
        if (col[1] > 75):
            col_to_drop.append(col[0])

race: 2.23% missing
weight: 96.86% missing
payer_code: 39.56% missing
medical_specialty: 49.08% missing
diag_1: 0.02% missing
diag_2: 0.35% missing
diag_3: 1.40% missing
max_glu_serum: 94.75% missing
A1Cresult: 83.28% missing

In [25]:
# drop columns with > 75% missing values
df_new = df.drop(columns=col_to_drop)

In [29]:
# drop columns that are not needed for model prediction
drop_col = ['payer_code', 'num_lab_procedures']
df_temp = df_new.drop(columns=drop_col)

In [30]:
# remove rows with missing race and diagnosis information
df_updated = df_temp.dropna(subset = ['race', 'diag_1', 'diag_2', 'diag_3'])

In [31]:
# check for duplicate rows 
ids['encounter_id'].duplicated().any()

np.False_

In [32]:
# check for inconsistencies in data formatting (inconsistent capitalization, spacing, etc)
for col in df_updated.columns:
    print(df_updated[col].value_counts(dropna=False))

encounter_id
149190       1
64410        1
500364       1
16680        1
35754        1
            ..
443847548    1
443847782    1
443854148    1
443857166    1
443867222    1
Name: count, Length: 98053, dtype: int64
patient_nbr
88785891     39
1660293      23
23199021     23
88227540     23
23643405     22
             ..
183087545     1
188574944     1
140199494     1
120975314     1
175429310     1
Name: count, Length: 68630, dtype: int64
race
Caucasian          75079
AfricanAmerican    18881
Hispanic            1984
Other               1484
Asian                625
Name: count, dtype: int64
gender
Female             52833
Male               45219
Unknown/Invalid        1
Name: count, dtype: int64
age
[70-80)     25306
[60-70)     21809
[80-90)     16702
[50-60)     16697
[40-50)      9265
[30-40)      3548
[90-100)     2717
[20-30)      1478
[10-20)       466
[0-10)         65
Name: count, dtype: int64
admission_type_id
1    52178
3    18194
2    17543
6     5135
5     4661
8      312
7       20
4       10
Name: count, dtype: int64
discharge_disposition_id
1     57610
3     13564
6     12626
18     3624
2      2049
22     1970
11     1606
5      1127
25      941
4       756
7       592
23      400
13      396
14      368
28      137
8       106
15       63
24       48
9        21
17       14
16       11
19        8
10        6
27        5
12        3
20        2
Name: count, dtype: int64
admission_source_id
7     55951
1     28356
17     6602
4      2945
6      1893
2      1031
5       846
3       179
20      160
9        49
8        15
22       12
10        7
14        2
11        2
25        2
13        1
Name: count, dtype: int64
time_in_hospital
3     17049
2     16441
1     13490
4     13434
5      9699
6      7320
7      5694
8      4276
9      2928
10     2287
11     1809
12     1424
13     1185
14     1017
Name: count, dtype: int64
medical_specialty
NaN                       48318
InternalMedicine          13967
Emergency/Trauma           7472
Family/GeneralPractice     7140
Cardiology                 5218
                          ...
Dermatology                   1
SportsMedicine                1
Speech                        1
Perinatology                  1
Neurophysiology               1
Name: count, Length: 73, dtype: int64
num_procedures
0    44574
1    20029
2    12383
3     9210
6     4811
4     4076
5     2970
Name: count, dtype: int64
num_medications
13    5885
12    5816
15    5621
11    5592
14    5520
      ...
70       2
75       2
81       1
79       1
74       1
Name: count, Length: 75, dtype: int64
number_outpatient
0     81680
1      8340
2      3514
3      2005
4      1078
5       521
6       297
7       153
8        98
9        83
10       57
11       41
13       31
12       30
14       28
15       20
16       15
17        8
20        7
21        7
18        5
22        5
19        3
27        3
24        3
35        2
29        2
36        2
26        2
33        2
25        2
23        2
42        1
39        1
34        1
28        1
37        1
38        1
40        1
Name: count, dtype: int64
number_emergency
0     86846
1      7550
2      2011
3       716
4       372
5       190
6        93
7        72
8        50
10       34
9        32
11       22
13       12
12       10
22        6
16        5
18        5
20        4
19        4
15        3
25        2
14        2
21        2
42        1
28        1
46        1
76        1
37        1
64        1
63        1
54        1
24        1
29        1
Name: count, dtype: int64
number_inpatient
0     64634
1     19067
2      7421
3      3346
4      1597
5       802
6       474
7       266
8       147
9       111
10       60
11       48
12       33
13       20
14       10
15        8
16        5
19        2
21        1
18        1
Name: count, dtype: int64
diag_1
428    6730
414    6374
786    3900
410    3514
486    3412
       ...
690       1
603       1
10        1
52        1
V51       1
Name: count, Length: 713, dtype: int64
diag_2
428    6517
276    6513
250    5412
427    4919
401    3613
       ...
123       1
884       1
V60       1
843       1
927       1
Name: count, Length: 740, dtype: int64
diag_3
250    11208
401     8090
276     5097
428     4491
427     3865
       ...
14         1
750        1
370        1
671        1
971        1
Name: count, Length: 786, dtype: int64
number_diagnoses
9     48687
5     10592
8     10388
7     10179
6      9988
4      5361
3      2751
16       40
13       16
10       16
11       11
12        9
15        8
14        7
Name: count, dtype: int64
metformin
No        78808
Steady    17677
Up         1017
Down        551
Name: count, dtype: int64
repaglinide
No        96530
Steady     1371
Up          107
Down         45
Name: count, dtype: int64
nateglinide
No        97362
Steady      657
Up           23
Down         11
Name: count, dtype: int64
chlorpropamide
No        97970
Steady       76
Up            6
Down          1
Name: count, dtype: int64
glimepiride
No        93066
Steady     4488
Up          315
Down        184
Name: count, dtype: int64
acetohexamide
No        98052
Steady        1
Name: count, dtype: int64
glipizide
No        85769
Steady    10991
Up          752
Down        541
Name: count, dtype: int64
glyburide
No        87792
Steady     8932
Up          791
Down        538
Name: count, dtype: int64
tolbutamide
No        98031
Steady       22
Name: count, dtype: int64
pioglitazone
No        90955
Steady     6756
Up          227
Down        115
Name: count, dtype: int64
rosiglitazone
No        91887
Steady     5908
Up          174
Down         84
Name: count, dtype: int64
acarbose
No        97754
Steady      286
Up           10
Down          3
Name: count, dtype: int64
miglitol
No        98016
Steady       31
Down          4
Up            2
Name: count, dtype: int64
troglitazone
No        98050
Steady        3
Name: count, dtype: int64
tolazamide
No        98016
Steady       36
Up            1
Name: count, dtype: int64
examide
No    98053
Name: count, dtype: int64
citoglipton
No    98053
Name: count, dtype: int64
insulin
No        45943
Steady    29368
Down      11843
Up        10899
Name: count, dtype: int64
glyburide-metformin
No        97384
Steady      660
Up            6
Down          3
Name: count, dtype: int64
glipizide-metformin
No        98040
Steady       13
Name: count, dtype: int64
glimepiride-pioglitazone
No        98052
Steady        1
Name: count, dtype: int64
metformin-rosiglitazone
No    98053
Name: count, dtype: int64
metformin-pioglitazone
No        98052
Steady        1
Name: count, dtype: int64
change
No    52774
Ch    45279
Name: count, dtype: int64
diabetesMed
Yes    75351
No     22702
Name: count, dtype: int64
readmitted
NO     52338
>30    34649
<30    11066
Name: count, dtype: int64

In [33]:
# remove one row with unknown gender value
df_updated.drop(df_updated[df_updated['gender'] == 'Unknown/Invalid'].index, inplace=True)

In [34]:
# remove null/unknown values from numerically mapped columns 

# admission - remove 5, 6, 8
df_updated = df_updated[~df_updated['admission_type_id'].isin([5, 6, 8])]

# discharge - remove 18, 25, 26
df_updated = df_updated[~df_updated['discharge_disposition_id'].isin([18, 25, 26])]

# admission source - remove 9, 15, 17, 20, 21  
df_updated = df_updated[~df_updated['admission_source_id'].isin([9, 15, 17, 20, 21])]

In [35]:
# change readmitted to binary values, where < 30 readmission is 1, otherwise 0

import numpy as np
df_updated['readmitted'] = np.where(df_updated['readmitted'] == '<30', 1, 0)

In [36]:
df_updated['readmitted'].value_counts(dropna=False)

readmitted
0    73857
1     9397
Name: count, dtype: int64

In [37]:
# create new features 

# create col for total hospitalizations 
df_updated['num_hospitalizations'] = df_updated.groupby('patient_nbr')['patient_nbr'].transform('count')

# procedures/length of stay
df_updated['avg_procedure'] = df_updated['num_procedures'] / df_updated['time_in_hospital'] 

# number of total visits
df_updated['total_visits'] = df_updated['number_outpatient'] + df_updated['number_emergency'] + df_updated['number_inpatient']

# number of med changes 
df_updated['num_med_changes'] = df_updated.loc[:, 'metformin':'metformin-pioglitazone'].isin(['Down', 'Up']).sum(axis=1)

# number of med increases 
df_updated['num_med_increase'] = df_updated.loc[:, 'metformin':'metformin-pioglitazone'].isin(['Up']).sum(axis=1)

In [ ]:
# drop medical speciality and medication info not needed for model prediction

df_final = df_updated.drop(columns=df_updated.loc[:, 'metformin':'metformin-pioglitazone'].columns)
df_final = df_final.drop(columns=['medical_specialty'])
df_final.columns

Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'change', 'diabetesMed',
       'readmitted', 'num_hospitalizations', 'avg_procedure', 'total_visits',
       'num_med_changes', 'num_med_increase'],
      dtype='str')

In [55]:
df_final.head(10)

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_procedures,...,diag_3,number_diagnoses,change,diabetesMed,readmitted,num_hospitalizations,avg_procedure,total_visits,num_med_changes,num_med_increase
1,149190,55629189,Caucasian,Female,[10-20),1,1,7,3,0,...,255,9,Ch,Yes,0,1,0.000000,0,1,1
2,64410,86047875,AfricanAmerican,Female,[20-30),1,1,7,2,5,...,V27,6,No,Yes,0,1,2.500000,3,0,0
3,500364,82442376,Caucasian,Male,[30-40),1,1,7,2,1,...,403,7,Ch,Yes,0,1,0.500000,0,1,1
4,16680,42519267,Caucasian,Male,[40-50),1,1,7,1,0,...,250,5,Ch,Yes,0,1,0.000000,0,0,0
5,35754,82637451,Caucasian,Male,[50-60),2,1,2,3,6,...,250,9,No,Yes,0,1,2.000000,0,0,0
6,55842,84259809,Caucasian,Male,[60-70),3,1,2,4,1,...,V45,7,Ch,Yes,0,1,0.250000,0,0,0
7,63768,114882984,Caucasian,Male,[70-80),1,1,7,5,0,...,250,8,No,Yes,0,1,0.000000,0,0,0
8,12522,48330783,Caucasian,Female,[80-90),2,1,4,13,2,...,38,8,Ch,Yes,0,1,0.153846,0,0,0
9,15738,63555939,Caucasian,Female,[90-100),3,3,4,12,3,...,486,8,Ch,Yes,0,1,0.250000,0,0,0
10,28236,89869032,AfricanAmerican,Female,[40-50),1,1,7,9,2,...,996,9,No,Yes,0,1,0.222222,0,0,0

In [56]:
# save processed dataframe 
df_final.to_csv('final_data.csv')

In [38]:
icd_data = pd.read_json('icd_codes.json')

In [39]:
icd_data

,code,desc,children
0,00-00,"Procedures And Interventions , Not Elsewhere C...","[{'code': '00', 'desc': 'Procedures And Interv..."
1,01-05,Operations On The Nervous System,"[{'code': '01', 'desc': 'Incision And Excision..."
2,06-07,Operations On The Endocrine System,"[{'code': '06', 'desc': 'Operations On Thyroid..."
3,08-16,Operations On The Eye,"[{'code': '08', 'desc': 'Operations On Eyelids..."
4,17-17,Other Miscellaneous Diagnostic And Therapeutic...,"[{'code': '17', 'desc': 'Other Miscellaneous P..."
5,18-20,Operations On The Ear,"[{'code': '18', 'desc': 'Operations On Externa..."
6,21-29,"Operations On The Nose, Mouth, And Pharynx","[{'code': '21', 'desc': 'Operation On Nose', '..."
7,30-34,Operations On The Respiratory System,"[{'code': '30', 'desc': 'Excision Of Larynx', ..."
8,35-39,Operations On The Cardiovascular System,"[{'code': '35', 'desc': 'Operations On Valves ..."
9,40-41,Operations On The Hemic And Lymphatic System,"[{'code': '40', 'desc': 'Operations On Lymphat..."
10,42-54,Operations On The Digestive System,"[{'code': '42', 'desc': 'Operations On Esophag..."
11,55-59,Operations On The Urinary System,"[{'code': '55', 'desc': 'Operations On Kidney'..."
12,60-64,Operations On The Male Genital Organs,"[{'code': '60', 'desc': 'Operations On Prostat..."
13,65-71,Operations On The Female Genital Organs,"[{'code': '65', 'desc': 'Operations On Ovary',..."
14,72-75,Obstetrical Procedures,"[{'code': '72', 'desc': 'Forceps, Vacuum, And ..."
15,76-84,Operations On The Musculoskeletal System,"[{'code': '76', 'desc': 'Operations On Facial ..."
16,85-86,Operations On The Integumentary System,"[{'code': '85', 'desc': 'Operations On The Bre..."
17,87-99,Miscellaneous Diagnostic And Therapeutic Proce...,"[{'code': '87', 'desc': 'Diagnostic Radiology'..."
18,001-139,Infectious And Parasitic Diseases,"[{'code': '001-009', 'desc': 'Intestinal Infec..."
19,140-239,Neoplasms,"[{'code': '140-149', 'desc': 'Malignant Neopla..."
20,240-279,"Endocrine, Nutritional And Metabolic Diseases,...","[{'code': '240-246', 'desc': 'Disorders Of Thy..."
21,280-289,Diseases Of The Blood And Blood-Forming Organs,"[{'code': '280', 'desc': 'Iron deficiency anem..."
22,290-319,Mental Disorders,"[{'code': '290-294', 'desc': 'Organic Psychoti..."
23,320-389,Diseases Of The Nervous System And Sense Organs,"[{'code': '320-327', 'desc': 'Inflammatory Dis..."
24,390-459,Diseases Of The Circulatory System,"[{'code': '390-392', 'desc': 'Acute Rheumatic ..."
25,460-519,Diseases Of The Respiratory System,"[{'code': '460-466', 'desc': 'Acute Respirator..."
26,520-579,Diseases Of The Digestive System,"[{'code': '520-529', 'desc': 'Diseases Of Oral..."
27,580-629,Diseases Of The Genitourinary System,"[{'code': '580-589', 'desc': 'Nephritis, Nephr..."
28,630-679,"Complications Of Pregnancy, Childbirth, And Th...","[{'code': '630-639', 'desc': 'Ectopic And Mola..."
29,680-709,Diseases Of The Skin And Subcutaneous Tissue,"[{'code': '680-686', 'desc': 'Infections Of Sk..."
30,710-739,Diseases Of The Musculoskeletal System And Con...,"[{'code': '710-719', 'desc': 'Arthropathies An..."
31,740-759,Congenital Anomalies,"[{'code': '740', 'desc': 'Anencephalus and sim..."
32,760-779,Certain Conditions Originating In The Perinata...,"[{'code': '760-763', 'desc': 'Maternal Causes ..."
33,780-799,"Symptoms, Signs, And Ill-Defined Conditions","[{'code': '780-789', 'desc': 'Symptoms', 'chil..."
34,800-999,Injury And Poisoning,"[{'code': '800-804', 'desc': 'Fracture Of Skul..."
35,V01-V91,Supplementary Classification Of Factors Influe...,"[{'code': 'V01-V09', 'desc': 'Persons With Pot..."
36,E000-E999,Supplementary Classification Of External Cause...,"[{'code': 'E000-E000', 'desc': 'External Cause..."

In [ ]:
# load in icd code data
import json
with open('icd_codes.json') as file:
    icd_raw_data = json.load(file)

In [ ]:
# test line to see how data is organized 
record = icd_raw_data[0]
print(record.get('children')[0].get('children')[0])

{'code': '00.0', 'desc': 'Therapeutic Ultrasound', 'children': [{'code': '00.01', 'desc': 'Therapeutic ultrasound of vessels of head and neck', 'children': []}, {'code': '00.02', 'desc': 'Therapeutic ultrasound of heart', 'children': []}, {'code': '00.03', 'desc': 'Therapeutic ultrasound of peripheral vascular vessels', 'children': []}, {'code': '00.09', 'desc': 'Other therapeutic ultrasound', 'children': []}]}

In [42]:
# extract icd data from nested format

icd_data = []

for category in icd_raw_data:
    primary_category = category.get('desc')
    sub_categories = category.get('children')
    for sub_category in sub_categories:
        sub_category_desc = sub_category.get('desc')
        codes = sub_category.get('children')
        for value in codes:
            code = value.get('code')
            code_desc = value.get('desc')
            icd_data.append({'code': code, 'description': code_desc, 'primary_category': primary_category, 'subcategory': sub_category_desc})

In [43]:
# save icd data to dataframe 
icd_code_df = pd.DataFrame(icd_data)

In [44]:
# export icd_dataframe 
icd_code_df.to_csv('icd_code.csv')